---
title: "Fishplot of tumors across multiple timepoints for the PBTA Cohort"
author: 'Antonia Chroni <chronia@chop.edu> for D3B'
date: "2023"
output:
  html_notebook:
    toc: TRUE
    toc_float: TRUE
---

# Method: Fishplot
https://github.com/chrisamiller/fishplot
https://www.biostars.org/tag/sciClone/ 


# Set up

```{r load-library}
suppressPackageStartupMessages({
  library(tidyverse)
  library(fishplot)
  # library(data.table)
  #library(R.utils)
 # library(clonevol)
 # library(devtools)
 # library(purrr)
 # library(flextable)
 # library(plyr)
})
```

# Directories and File Inputs/Outputs

```{r set-dir-and-file-names}
# Detect the ".git" folder -- this will be in the project root directory
# Use this as the root directory to ensure proper sourcing of functions 
# no matter where this is called from
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "tumor-clone-inference")
files_dir <- file.path(root_dir, "analyses", "sample-distribution-analysis", "results")
maf_files_dir <- file.path(root_dir, "analyses", "tmb-vaf-longitudinal", "results")

# File path to results directory
results_dir <-
  file.path(analysis_dir, "results")
if (!dir.exists(results_dir)) {
  dir.create(results_dir)
}

# Input files
pbta_file <- file.path(files_dir, "pbta.tsv") # file from add-sample-distribution module
maf_file <- file.path(maf_files_dir, "maf.tsv")
genomic_paired_file <- file.path(files_dir, "genomic_assays_matched_time_points.tsv") # file from add-sample-distribution module
Diffuse_midline_glioma_PT_KTRJ8TFY_file <- file.path(results_dir, "CloneFinder_output", "Diffuse_midline_glioma_PT_KTRJ8TFYsnv_CloneFinder.txt") 

#source(paste0(analysis_dir, "/util/function-create-df.R"))
```

# Load data

```{r load-inputs}
maf_df <- readr::read_tsv(maf_file, guess_max = 100000, show_col_types = FALSE) 

pbta_df <- readr::read_tsv(pbta_file, guess_max = 100000, show_col_types = FALSE) %>% 
  filter(!experimental_strategy == "RNA-Seq")

genomic_paired_df <- readr::read_tsv(genomic_paired_file, guess_max = 100000, show_col_types = FALSE) %>% 
  select(!c(cancer_group, experimental_strategy)) %>% 
  left_join(pbta_df, by = c("Kids_First_Participant_ID")) %>% 
  dplyr::mutate(cg_id_kids = paste(cg_id, Kids_First_Participant_ID, sep = "_"),
         cg_id_kids = str_replace(cg_id_kids, "/", "_"),
         cg_id_kids = str_replace(cg_id_kids, "-", "_"),
         cg_id_kids = str_replace_all(cg_id_kids, " ", "_"),
         td_bs_id = paste(tumor_descriptor, Kids_First_Biospecimen_ID, sep = "_"))

df <- genomic_paired_df %>% 
  left_join(maf_df, by = c("Kids_First_Biospecimen_ID")) 

df_samples <- print(length(unique(df$cg_id_kids)))








# Read clone frequency files from CloneFinder output directory
# Process the file to match the example from the Fishplot matrix
Diffuse_midline_glioma_PT_KTRJ8TFY_df <- readr::read_table(Diffuse_midline_glioma_PT_KTRJ8TFY_file) %>% 
  tidyr::separate(Tumor, c("timepoint", "bs_id"), sep = '_', remove = FALSE) %>% 
  select(!bs_id) %>% 
  pivot_wider(names_from = "timepoint", values_from = c(Clone1, Clone2, Clone3), values_fill = 0) 

# clone df
clone1_df <- Diffuse_midline_glioma_PT_KTRJ8TFY_df %>% 
  pivot_wider(names_from = "timepoint", values_from = "Clone1") %>% 
  select(-c("Clone2", "Clone3"))

clone2_df <- Diffuse_midline_glioma_PT_KTRJ8TFY_df %>% 
   pivot_wider(names_from = "timepoint", values_from = "Clone2") %>% 
  select(-c("Clone1", "Clone3"))

clone3_df <- Diffuse_midline_glioma_PT_KTRJ8TFY_df %>% 
 pivot_wider(names_from = "timepoint", values_from = "Clone3") %>% 
  select(-c("Clone2", "Clone1"))


  # Merge df
  merge_df <- clone1_df %>% 
    full_join(clone2_df, by = c("Tumor", "Diagnosis", "Deceased")) %>% 
    full_join(clone3_df, by = c("Tumor", "Diagnosis", "Deceased")) %>% 
    #mutate_all(funs(replace_na(.,0))) %>% 
    select(!Tumor) %>% 
    as.data.frame() 
  
test <- subset(merge_df, !Diagnosis == "0" & !Deceased == "0")
test

  

```

# Process Data for Fishplot

```{r df-cg-id-kids}
# Save results by cg_id_kids
cg_id_kids_names <- unique(as.character(df$cg_id_kids))
cg_id_kids_names <- sort(cg_id_kids_names, decreasing = FALSE)
print(cg_id_kids_names)

cg_id_kids_names = "Diffuse_midline_glioma_PT_KTRJ8TFY"
# Loop through cg_sum
for (x in seq_along(cg_id_kids_names)){
  print(x)
  
   df_sub <- df %>%
    filter(cg_id_kids == cg_id_kids_names[x]) %>% 
    distinct(tumor_descriptor, .keep_all = TRUE) %>% 
    select(cg_id_kids, tumor_descriptor, age_at_event_days,
           age_at_diagnosis_days, age_last_update_days, age_at_chemo_start, 
           age_at_radiation_start) %>% 
     mutate(day = case_when(grepl("Diagnosis", tumor_descriptor) ~ age_at_diagnosis_days,
                            grepl("Deceased", tumor_descriptor) ~ age_last_update_days))
   
   # In this example we have Diagnosis and Recurrence (2 timepoints)
   # age_at_event_days: age at day specimen was collected
   # timepoints = df_sub$age_at_event_days
   timepoints = df_sub$day
   
   # provide a matrix with the fraction of each population
   # present at each timepoint
   frac.table = matrix(merge_df,
                       ncol = length(timepoints))
    
    #provide a vector listing each clone's parent
    #(0 indicates no parent)
    parents = c(1, 1)
    
     #create a fish object
    fish = createFishObject(frac.table, 
                            parents,
                            timepoints = timepoints)

    #calculate the layout of the drawing
    fish = layoutClones(fish)
    
    # Define days to show as significant timepoints in the Fishplot
    day_min = min(df_sub$day)
    day_max = max(df_sub$day)

    #draw the plot, using the splining method (recommended)
    #and providing both timepoints to label and a plot title
    fishPlot(fish,
             shape = "spline", 
             title.btm = cg_id_kids_names,
             cex.title = 0.5, 
             vlines = c(0, 150), 
             vlab = c(day_min, day_max))
}
  




#provide a list of timepoints to plot
    #You may need to add interpolated points to end up with the desired
    #visualization. Example here was actually sampled at days 0 and 150
    timepoints=c(0,30,75,150)      

    #provide a matrix with the fraction of each population
    #present at each timepoint
    frac.table = matrix(
      c(100, 45, 00, 00,
         02, 00, 00, 00,
         02, 00, 02, 01,
         98, 00, 95, 40),
      ncol=length(timepoints))

    #provide a vector listing each clone's parent
    #(0 indicates no parent)
    parents = c(0,1,1,3)

    #create a fish object
    fish = createFishObject(frac.table,parents,timepoints=timepoints)

    #calculate the layout of the drawing
    fish = layoutClones(fish)

    #draw the plot, using the splining method (recommended)
    #and providing both timepoints to label and a plot title
    fishPlot(fish,shape="spline",title.btm="Sample1",
             cex.title=0.5, vlines=c(0,150), 
             vlab=c("day 0","day 150"))
    
    
    
    

















df_temp <- df %>%
  select("cg_id_kids", "td_bs_id", "mut_id", "Chr", "Position", "Wild", "Mut", "XX:ref", "XX:alt")

# Save results by cg_id_kids
cg_id_kids_names <- unique(as.character(df_temp$cg_id_kids))
cg_id_kids_names <- sort(cg_id_kids_names, decreasing = FALSE)
print(cg_id_kids_names)

# Loop through cg_sum
for (x in seq_along(cg_id_kids_names)){
  print(x)

  df_sub <- df_temp %>%
    filter(cg_id_kids == cg_id_kids_names[x]) 
 
  # We will define samples
  td_bs_id_names <- unique(as.character(df_sub$td_bs_id))
  print(td_bs_id_names)
  
  # Create empty list for df
  df_list <- list() 
  
  # Run loop for each td_bs_id_names
  for (i in seq_along(td_bs_id_names)) {
    print(i)
   
    td_bs_df <- df_sub %>%
      filter(td_bs_id == td_bs_id_names[i])
    
    # Run function 
    m <- create_df(df = td_bs_df, 
                   sample_id = td_bs_id_names[i],
                   cg_kid = cg_id_kids_names[x])
  
    # Assign name to df and store all df in list
    df_name <- paste(cg_id_kids_names[x], td_bs_id_names[i], sep = "-")
    df <- assign(df_name, m)
    df_list[[df_name]] <- df
    
    # Merge all df per `cg_kids_id`
    # Assign name to all_df
    name <- paste(cg_id_kids_names[x])
    
    cg_kids_df <- df_list %>% 
      reduce(full_join, by = c("cg_id_kids", "mut_id", "Chr", "Position", "Wild", "Mut")) %>% 
      replace(is.na(.), 0) %>% 
      write.table(file.path(CloneFinder_input_dir, paste0(name, ".txt")), 
                  sep = "\t", 
                  row.names = FALSE, 
                  quote = FALSE, 
                  fileEncoding = "UTF-8")
  }
          
}
```

# Make list with input files for CloneFinder

```{r samples-path}
# File path 
samples_path_dir <-
  file.path(analysis_dir, "CloneFinderAPI", "clonefinder_py3", "CloneFinder_input")

samples_path_df <- df_temp %>%
  select(cg_id_kids) %>% 
  unique() %>% 
  mutate(path = samples_path_dir,
         additional = 1) %>% 
      write.table(file.path(CloneFinder_input_dir, paste0(name, ".txt")), 
                  sep = "\t", 
                  row.names = FALSE, 
                  quote = FALSE, 
                  fileEncoding = "UTF-8")
```

# or try this with the python script

```{r samples-path-python}
########################################
DMG <- df %>% 
  filter(cgGFAC == "DMG")
print(length(unique((DMG$cg_id_kids))))

HGG <- df %>% 
  filter(cgGFAC == "HGG")
print(length(unique((HGG$cg_id_kids))))

LGG <- df %>% 
  filter(cgGFAC == "LGG")
print(length(unique((LGG$cg_id_kids))))

Other <- df %>% 
  filter(cgGFAC == "Other")
print(length(unique((Other$cg_id_kids))))

########################################
# Save python script per each sample
cg_id_kids_names <- unique(as.character(df$cg_id_kids))
cg_id_kids_names <- sort(cg_id_kids_names, decreasing = FALSE)
print(cg_id_kids_names)

library(data.table)
# create empty vector 
#vector1 = c() 

# Loop through cg_sum
for (i in seq_along(cg_id_kids_names)){
  input_path_dir <-
    # file.path(analysis_dir, "CloneFinderAPI", "clonefinder_py3", "CloneFinder_input")
    file.path("/Users/chronia/CHOP/software", "CloneFinderAPI", "clonefinder_py3", "input")

  input_python_script <- paste("python clonefinder.py snv ./input/", cg_id_kids_names[i], ".txt", sep = "") 
  #vector1 = c(input_python_script, i)
  print(input_python_script)
}

# fwrite(input_python_script, file.path(results_dir, file = "input_python_script.csv"))
```  

```{r}
sessionInfo()
```

